config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  root "teachers#index"
  resources :teachers do
    collection do
      get 'list'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/teacher.rb
class Teacher < ApplicationRecord

  FILTER_PARAMS = %i[name column direction].freeze

  scope :by_name, ->(query) { where('teachers.name like ?', "%#{query}%") }
  scope :by_school, ->(school) { where(school: school) if school.present? }

  def self.filter(filters)
    Teacher
      .all
      .by_name(filters['name'])
      .by_school(filters['school'])
      .order("#{filters['column']} #{filters['direction']}")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
end

app/controllers/concerns/filterable.rb
module Filterable
  def filter!(resource)
    store_filters(resource)
    apply_filters(resource)
  end

  private

  def store_filters(resource)
    session["#{resource.to_s.underscore}_filters"] = {} unless session.key?("#{resource.to_s.underscore}_filters")

    session["#{resource.to_s.underscore}_filters"].merge!(filter_params_for(resource))
  end

  def filter_params_for(resource)
    params.permit(resource::FILTER_PARAMS)
  end

  def apply_filters(resource)
    resource.filter(session["#{resource.to_s.underscore}_filters"])
  end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :set_teacher, only: %i[ show edit update destroy ]
  include Filterable

  # GET /teachers or /teachers.json
  def index
    @pagy, @teachers = pagy(filter!(Teacher), items: 25)
  end

  # GET /teachers/1 or /teachers/1.json
  def show
  end

  # GET /teachers/new
  def new
    @teacher = Teacher.new
  end

  # GET /teachers/1/edit
  def edit
  end

  # POST /teachers or /teachers.json
  def create
    @teacher = Teacher.new(teacher_params)

    respond_to do |format|
      if @teacher.save
        format.html { redirect_to teacher_url(@teacher), notice: "Teacher was successfully created." }
        format.json { render :show, status: :created, location: @teacher }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  def list
    @pagy, @teachers = pagy(filter!(Teacher), items: 25)

    render(partial: 'teachers', locals: { teachers: @teachers })
  end

  # PATCH/PUT /teachers/1 or /teachers/1.json
  def update
    respond_to do |format|
      if @teacher.update(teacher_params)
        format.html { redirect_to teacher_url(@teacher), notice: "Teacher was successfully updated." }
        format.json { render :show, status: :ok, location: @teacher }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1 or /teachers/1.json
  def destroy
    @teacher.destroy

    respond_to do |format|
      format.html { redirect_to teachers_url, notice: "Teacher was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_teacher
    @teacher = Teacher.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def teacher_params
    params.require(:teacher).permit(:name, :school, :year)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/teachers_helper.rb
# frozen_string_literal: true

# Hotwire helpers for teachers resource
module TeachersHelper
  def sort_link(column, label)
    if column == params[:column]
      link_to(label, list_teachers_path(column: column, direction: next_direction))
    else
      link_to(label, list_teachers_path(column: column, direction: 'asc'))
    end
  end

  def next_direction
    params[:direction] == 'asc' ? 'desc' : 'asc'
  end

  def sort_indicator
    tag.span(class: "sort sort-#{params[:direction]}")
  end

  def build_order_link(column:, label:)
    if column == session.dig('teacher_filters', 'column')
      link_to(label, list_teachers_path(column: column, direction: next_direction))
    else
      link_to(label, list_teachers_path(column: column, direction: 'asc'))
    end
  end

  def next_direction
    session['teacher_filters']['direction'] == 'asc' ? 'desc' : 'asc'
  end

  def sort_indicator
    tag.span(class: "sort sort-#{session['teacher_filters']['direction']}")
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex-col">
      <%= yield %>
    </main>
  </body>
</html>

app/views/teachers/_form.html.erb
<%= form_with(model: teacher, class: "contents") do |form| %>
  <% if teacher.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>

      <ul>
        <% teacher.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :school %>
    <%= form.text_field :school, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :year %>
    <%= form.datetime_field :year, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/teachers/_pager.html.erb
<div id="pager" class="min-w-full my-8 flex justify-between">
  <div>
    <% if pagy&.prev %>
      <%= link_to(
        "< Previous page",
        list_teachers_path(page: pagy.prev),
        class: "rounded py-3 px-5 bg-gray-600 text-white block hover:bg-gray-800",
        data: {
          turbo_action: "advance"
        }
      ) %>
    <% end %>
  </div>
  <div class="text-right">
    <% if pagy&.next %>
      <%= link_to(
        "Next page >",
        list_teachers_path(page: pagy.next),
        class: "rounded py-3 px-5 bg-gray-600 text-white block hover:bg-gray-800",
        data: {
          turbo_action: "advance"
        }
      ) %>
    <% end %>
  </div>
</div>

app/views/teachers/_teacher.html.erb
<div id="<%= dom_id teacher %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= teacher.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">School:</strong>
    <%= teacher.school %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Year:</strong>
    <%= teacher.year %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this teacher", teacher, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this teacher', edit_teacher_path(teacher), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/teachers/_teachers.html.erb
<div class="flex justify-end mb-4">
  <%= form_with url: list_teachers_path, method: :get, data: { controller: "search-form", search_form_target: "form", turbo_frame: "teachers" } do |form| %>

    <%= form.text_field :name,
      placeholder: "Search by name",
      value: session.dig('teacher_filters', 'name'),
      class: "border border-blue-500 rounded p-2",
      autocomplete: "off",
      id: 'search-bar',
      data: { action: "input->search-form#search" }
    %>
  <% end %>
</div>

<%= turbo_frame_tag "teachers", class: "shadow overflow-hidden rounded border-b border-gray-200" do %>
  <table class="table-auto border border-blue-200 rounded-md mt-4 flex-col w-full">
    <thead class='bg-blue-500 text-white'>
      <tr class= "">
        <th id="teachers-name" class="border border-blue-300 text-left py-3 px-6 uppercase font-semibold text-sm hover:cursor-pointer relative">
          <%= sort_indicator if session.dig('teacher_filters', 'column') == "name" %>
          <%= build_order_link(column: "name", label: "Name") %>
        </th>
        <th id='teachers-school'class="border border-blue-300 text-left py-3 px-6 uppercase font-semibold text-sm hover:cursor-pointer relative">
          <%= sort_indicator if session.dig('teacher_filters', 'column') == "school" %>
          <%= build_order_link(column: "school", label: "School") %>
        </th>
        <th id='teachers-year' class="border border-blue-300 text-left py-3 px-6 uppercase font-semibold text-sm hover:cursor-pointer relative">
          <%= sort_indicator if session.dig('teacher_filters', 'column') == "year" %>
          <%= build_order_link(column: "year", label: "Year") %>
        </th>
      </tr>
    </thead>
    <% @teachers.each do |teacher| %>
      <tbody>
        <tr class= "border-collapse border border-indigo-400">
          <td class="border border-blue-400 bg-slate-200"><%= teacher.name%></td>
          <td class="border border-blue-400 bg-slate-200"><%=teacher.school %></td>
          <td class="border border-blue-400 bg-slate-200"><%=teacher.year&.year %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="min-w-full">
    <%= render "pager", pagy: @pagy %>
  </div>
<% end %>

app/views/teachers/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing teacher</h1>

  <%= render "form", teacher: @teacher %>

  <%= link_to "Show this teacher", @teacher, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to teachers", teachers_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/teachers/index.html.erb
<div class="flex-col justify-center">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>
  <div class="flex-col">
    <h1 class="font-bold text-3xl mb-4">Find or Add a Teacher</h1>
    <%= link_to 'Add a Teacher', new_teacher_path, class: "rounded-lg w-48 py-3 px-5 bg-blue-600 text-white block font-medium", id:'create_teacher' %>
  </div>

  <div class="flex-col justify-center">
    <%= render 'teachers', teachers: @teachers %>
  </div>
</div>

app/views/teachers/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New teacher</h1>

  <%= render "form", teacher: @teacher %>

  <%= link_to 'Back to teachers', teachers_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/teachers/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @teacher %>

    <%= link_to 'Edit this teacher', edit_teacher_path(@teacher), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this teacher', teacher_path(@teacher), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to teachers', teachers_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>